Update crud and add chat
eb59162/ServerEndProject pull request #6
Opened 2024-06-24 20:45 UTC by eb59162

2024-06-25 16:48 UTC, shirashtub commented
אסתי,
עבודה יפה
נראה לי כדאי להפריד לשתי בראנצים

2024-06-25 16:48 UTC, shirashtub requested changes

2024-06-25 16:48 UTC, shirashtub commented on Controlers/ControllerStory.js
> +             new: true },
עושים את ה-new בצומדיים נוספים

2024-06-25 16:48 UTC, shirashtub commented on Controlers/ControllerUser.js
> +        const deleteUser = await Data.findOneAndDelete({ id: id })
אפשר לכתוב רק { id }

2024-06-25 16:48 UTC, shirashtub commented on Models/ModelStory.js
> +    Category: {type: String,
אולי כדאי להגדיר ENUM של קטגוריות

2024-06-25 16:49 UTC, shirashtub approved these changes

2024-06-26 08:17 UTC, eb59162 commented
תודה,
איך אני אחלק את זה עכשיו ל2 בראנצ'ים?

2024-06-26 08:27 UTC, shirashtub commented
export enum TaskStatus {
    ToDo = 1,
    InProgress = 2,
    Completed = 3
}
דוגמא ל-enum
תשני את הערכים

2024-06-26 09:34 UTC, eb59162 commented
תודה רבה,

אני בעז"ה אשב על זה כשיהיה לי זמן 

איך אני מחלקת ל2 בראנצים אם אני על אותו פרויקט ויש לי בו את כל השינויים?

2024-06-26 09:42 UTC, shirashtub commented
בבראנצ הנוכחי את מוחקת את ה-chat
ופותחת בראנצ חדש עבורו

2024-06-26 11:08 UTC, eb59162 commented
תודה רבה

2024-06-26 11:09 UTC, eb59162 commented
התחלתי לעבוד על הקליינט, את יכולה להצטרף כשיהיה לך זמן

2024-06-26 20:05 UTC, closed without merging